apiVersion: apps/v1
kind: Development
metadata:
  name: myapp-argocd
  namespace: myapp
  specs:
    selector:
      matchLabels:
        app: myapp-argocd
    replicas: 2
    template:
      metadata:
        labels:
          app: myapp-argocd
      specs:
        containers:
        - name: myapp-argocd
          image: nanajanashia/argocd-app:1.0
          ports:
            containerPort: 8080
